### ISSUE TITLE
vips errors for invalid JPEG files

### ISSUE THREAD

**Issue by faucetlol** [Earlopain/reverser#104]
I've noticed quite a lot of JPEG files (all from FurAffinity, surprise surprise) have been failing with various reasons related to invalid JPEG files:

`Vips::Error: VipsJpeg: Invalid SOS parameters for sequential JPEG VipsJpeg: Invalid SOS parameters for sequential JPEG`
`Vips::Error: VipsJpeg: Premature end of input file`

Normally vips would just proceed, but this line explicitly causes it to fail preventing the submission file from being created:
https://github.com/Earlopain/reverser/blob/00fbaa12f307fc66cc67570386cc02bdaa0a680f/app/models/submission_file.rb#L102

**Comment by Earlopain** [comment]
Fairly sure these won't be able to be uploaded to e6. Is this just one artist or a general occurrence?

**Comment by faucetlol** [comment]
I think it's about 4 different artists that I'm watching that have been uploading corrupt files, starting over the past few weeks, so it's possible that FA made a recent-ish change to allow corrupt files to be uploaded. e6 does indeed reject these files, but I guess it's always possible to just recreate it as a non-corrupt file if I _did_ want to upload it. 

Most of the failed files have actually just been WIPs (I suspect some sort of screen clipping tool is causing it, but that's not really relevant here) so I wouldn't actually want to upload them anyway - it's mostly an annoyance that I just had to go discard 16 jobs that had already retried between 8 and 15 times each at something that's going to fail every single time.

**Comment by Earlopain** [comment]
Can you give me an example of one of these galleries?

I think an acceptable solution here would be to mark the files as corrupt instead of discarding them like this. I don't know common it is to download files and they get corrupted during transit without that raising an error, which is one of the reasons why things just get retried (though the current 25 tries is excessive here to say the least). Seems like something that doesn't really happen and I was overly defensive.

Almost all supported sites allow unauthenticated file access and don't expire their urls (with the exception of DeviantArt) so they can just be redownloaded, as long as the file still exists.

**Comment by faucetlol** [comment]
- https://www.furaffinity.net/user/katsumizi/
- https://www.furaffinity.net/user/joonkorner/
- https://www.furaffinity.net/user/boreduser/

Some of the offending files have since been deleted, so I'm not sure how many of these have corrupt files anymore, but https://www.furaffinity.net/view/54291207/ is an example in katsumizi's gallery that definitely still exists.
