### ISSUE TITLE
Wrong link in nav bar

### ISSUE THREAD

**Issue by mm12** [Earlopain/reverser#112]
The banner page's link for "Selenium" goes to `localhost:7900`, however if one was using a separate device, this would not work

**Comment by faucetlol** [comment]
I run Reverser on my server, so I have this problem too. I've altered this line to make the link work:

https://github.com/Earlopain/reverser/blob/fc80da387b3947351408f53239cbdf2f873da269/app/views/application/_navbar.html.erb#L12

Though it would probably be better if the hostname was configurable instead of needing to edit files.

**Comment by Earlopain** [comment]
Give this a try. I'm able to access it both through localhost and when using direct ip.

**Comment by faucetlol** [comment]
LGTM
