### ISSUE TITLE
Opinion on adding file mime type to the stats?

### ISSUE THREAD

**Issue by DontTalkToMeThx** [Earlopain/reverser#122]
On my local clone, I've added the mime type to show after the size, which I found to be very helpful in determining which duplicate to add to my backlog.

![lekxph_18634 1](https://github.com/Earlopain/reverser/assets/61888458/20f0d6e6-d59b-43d5-9a4f-1b442d58b8ae)

I was wondering if this would be worth adding directly to the app.

```rb
<div class="submission-file-stats">
  <%= site_icon artist_url %>
  <%= "#{submission_file.width}x#{submission_file.height}" %>, 
  <%= number_to_human_size submission_file.size %>, 
  <%= "#{submission_file.content_type.split('/', 2)[1]}" %>
</div>
```
Forgive me if this is some wildly inefficient way of doing this, ruby is not my best language.

**Comment by faucetlol** [comment]
I usually just mouseover the direct link to see the filename, but showing the MIME type probably isn't a bad thing. Especially since FA filenames frequently lie.

**Comment by DontTalkToMeThx** [comment]
Yeah I suppose I could do that, this just happened to save more time lol

**Comment by Earlopain** [comment]
Sounds fine to do. You can `Marcel::TYPE_EXTS[content_type].first` to get the extension which in theory also works for something like `application/x-shockwave-flash` and also gives the more familiar `jpg`. That's private API but whatever, existing tests should be good enough. Doing `upcase` might look better since everything else there already is as well

**Comment by DontTalkToMeThx** [comment]
Opened #123
