### ISSUE TITLE
Artist page errors when post is deleted

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#53]
Trying to view most the pages for artists now presents me with ```undefined method `[]' for nil:NilClass post_json["file_url"] || post_json["file"]["url"]``` because the posts are deleted and have no `file_url` - manually setting `post_is_deleted` to true makes the page render but there's potentially thousands of these and that sounds painful :(

I ran the migrations when I updated and it didn't seem to help

**Comment by faucetlol2** [comment]
Nevermind... ran `006_fill_post_is_deleted_field.rb` and it works now, didn't realise it wasn't a migration.

**Comment by Earlopain** [comment]
I wanted to make it work out of the box, but that wasn't an interaction I thought about. Whoops.

Any idea how I could make it clear that there might be something that needs to be done manually? I started out with putting stuff like this in the migration itself, but as you found out  yourself on initial setup that isn't all that great of a solution. Models get removed, methods renamed, etc. so that the migration might not work anymore in the future.

**Comment by faucetlol2** [comment]
I'll be honest and say you're probably asking the wrong person here, the majority of the things I make never leaves my own computer. I presume just keeping the migration up to date to account for things being changed isn't really a viable option either since there's no real way of telling which version the user is migrating from. 

If it can't be automated, I can't really think of anything better than just including it in the commit description, since the commit history is pretty much analogous to a changelog in a project like this.

**Comment by Earlopain** [comment]
Fair. I'll try to remember and put it in the description from now on and not break stuff when you didn't run it yet (which I already intended).

Btw, feel free to make those feature requests you talked about.
