### ISSUE TITLE
Move some named volumes to host volumes

### ISSUE THREAD

**Issue by Earlopain** [Earlopain/reverser#58]
I'm going to move `active_storage`, `db_data` and `iqdb_data` to host volumes and make their path configurable by an environment variable you will need to set in a `.env` file.

I already moved my `active_storage` to an internal HDD a while ago, but the absolute path to that I can't commit obviously.
The paths will be
* `${REVERSER_DATA_PATH}/active_storage`
* `{REVERSER_DATA_PATH}/db`
* `{REVERSER_DATA_PATH}/iqdb`

You are able to set absolute paths in the dockerfile, `/run/media/earlopain/H2/reverser_active_storage:/app/public/storage` is what I have currently, and this is what I'd like to generalize via the environment variable.

@faucetlol2 can you copy your data from the named volumes to some other folder and put these paths in the dockerfile for now? Once you're done I can make the changes. On linux the volumes are saved under `/var/lib/docker/volumes/`, I just had to copy my volume somewhere else and that was it.

**Comment by faucetlol2** [comment]
Not able to do this for a little while, but it should be fine to make the changes as long as I do this before pulling the latest changes right?

**Comment by Earlopain** [comment]
I moved my folder at least two months ago already, I can wait a bit more (incredible that I haven't commited that change accidentally already). Just ping me when you're ready, that'll be fine.

**Comment by faucetlol2** [comment]
I've spent quite a while trying to get this to work with no success - I moved the files just fine but I can't get the changes to the docker compose file to actually work. I've tried using the variable and just setting absolute paths, I'm not sure if I'm missing any additional steps that Windows requires or if it's just yet another reason that trying to do anything development related in Windows causes physical pain.

So far I've tried

- Adding `COMPOSE_CONVERT_WINDOWS_PATHS=1` to the `.env` file.
- Different drives, i.e. using C:/ rather than the internal HDD I wanted to move the files to.
- Different variations of the path, using `/c/` rather than `C:/`, encasing the string in quotes, trying both `/` and `\` variants of everything, etc
- Moving the volume back to its original location and reverting `docker-compose.yml` back to how it was works fine, so nothing happened to the files during the move.

I'm probably gonna give up for now and just remain on the current version until I've got more time to figure it out, unless you've got any ideas. This inconvenience has bumped "go back to using Linux on my main PC" quite high up on my personal to-do list either way.

**Comment by Earlopain** [comment]
Yeah, no idea how it works on windows. I have dual boot lying around, I'll commit what I currently have and fix up potential issues I find when trying to get it working there. Hopefully I can come up with something that works on both OSes

**Comment by Earlopain** [comment]
I've got it working on Windows with master, at least for me. This is my configuration:

.env
```
REVERSER_DATA_PATH=C:\Users\Earlopain\Desktop\reverser_data
```

![image](https://user-images.githubusercontent.com/14981592/192577713-268a733b-073f-4f80-af17-3f08bc245117.png)

The problem I was running into was with solargraph, the ruby diagnostics tool I'm using. I used the environment variable `PWD`, which doesn't exist on Windows. It also wouldn't have worked regardless, since it needs to mount the folder into the exact same path as on the host, and that is simply not possible with Windows as host and Linux containers. The solution is to just not start the solargraph service on windows, and that is now controlled through the .env file as well.

Maybe it works for you as well now?

**Comment by faucetlol2** [comment]
Those changes didn't work either, after using `docker-compose down -v` and creating a fresh install everything seems to be fine.

Copying the old volumes back into the fresh install breaks it again. Maybe Docker for Windows just handles volumes in a different strange way? I'm perfectly happy starting fresh again because I probably shouldn't need to do this again now it's all safely on my SSD with plenty of storage space. I could probably get it back to how it was by dumping the database or something but I can't really be bothered, it'll only take a few hours to get the iqdb data back.

**Comment by Earlopain** [comment]
Yeah, I was starting fresh myself on Windows too.

Just one more thing you could check: I _think_ the actual files were in a `_data` folder for me in the volumes, but that one shouldn't be copied over with the rest, only its content. `active_storage/_data/other_stuff` vs `active_storage/other_stuff`.
