### ISSUE TITLE
Missing commands: sass, tsc, esbuild

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#74]
Just upgraded from dbe5cb5a958c5090cea23e4761defba15c459760 to 756b8fd0e636e943fe07dc51ca88218775282f9f. These 3 commands always seem to be missing pretty much every time a rebuild is required. Not a big deal since it's easy to get working again with yarn, but I assume it should be doing that automatically.

```
reverser-reverser-1  | 05:55:48 css.1      | command not found: sass
reverser-reverser-1  | 05:55:48 tsc.1      | command not found: tsc
reverser-reverser-1  | 05:55:48 js.1       | command not found: esbuild
```

**Comment by Earlopain** [comment]
You need to run yarn install inside the container. It uses a named volume, which doesn't get updated when doing a build.

I haven't found a solution for this yet. I tried moving node_modules out of /app so that the host folder doesn't overlay and hide it, but no luck. If I would not mount something there the node_modules from the host would be used, which is also not great.
