### ISSUE TITLE
Infinite recursion in Inkbunny scraper

### ISSUE THREAD

**Issue by faucetlol2** [Earlopain/reverser#77]
`make_request` and `fetch_sid` just infinitely call each other in a loop.

https://github.com/Earlopain/reverser/blob/9ea9c1897fc09bfcee73d2a92efd114eaf7af212/app/logical/scraper/inkbunny.rb#L87-L100

**Comment by Earlopain** [comment]
In a previous [commit](https://github.com/Earlopain/reverser/commit/bd4620d77da80880575d1890443d6a2a7903ca1c) I moved network requests out of the construction of scrapers, but missed this.

In the future I want to switch to fetching this information on-demand instead of caching it for a set amount of time.
A bunch of scrapers have pretty low cache durations, twitter especially. I know that the tokens are more durable than an hour, but not how long exactly. So making requests and fetching the necessary stuff again when I make requests with expired tokens would be nice to have. Furaffinity as well, I set it to 2 weeks but it's valid for much longer.
