### ISSUE TITLE
Tumblr throws "no implicit conversion of String into Integer" when ratelimited

### ISSUE THREAD

**Issue by DonovanDMC** [Earlopain/reverser#95]
> no implicit conversion of String into Integer
> /app/app/logical/scraper/tumblr.rb:25:in \`fetch_next_batch'
> /app/app/logical/scraper/base.rb:25:in \`fetch_and_save_next_submissions'
> /app/app/jobs/scrape_artist_url_job.rb:12:in \`perform'

```
{
  "meta": {
    "status": 429,
    "msg": "Limit Exceeded"
  },
  "response": [

  ],
  "errors": [
    {
      "title": "Limit Exceeded",
      "code": 0,
      "detail": "Measly little error. Try again."
    }
  ]
}
```

**Comment by DonovanDMC** [comment]
This is happening specifically with `https://wwfleurfurr.tumblr.com`, I can't manage a full download before it starts failing

**Comment by Earlopain** [comment]
Tumblr is limited to 1000 calls per hour and 5000 per day. Surely this blog doesn't have more than 20k posts?

Scraping always starts from the beginning after failure because it doesn't save state. You should be getting more posts as it continously manages to go further along. A page is 20 items, so on first try it should manage about 950 posts, after that about 910 since it wastes a few calls paginating back, and so on.

**Comment by DonovanDMC** [comment]
It just might
```
{
  "path": "https://api.tumblr.com/v2/blog//posts/photo",
  "method": "get",
  "response_code": 429,
  "request_params": {
    "query": {
      "npf": true,
      "limit": 20,
      "offset": 15100,
      "reblog_info": true
    },
    "headers": {
      "Authorization": "[FILTERED]"
    }
  }
}
```

```
{
  "meta": {
    "status": 429,
    "msg": "Limit Exceeded"
  },
  "response": [

  ],
  "errors": [
    {
      "title": "Limit Exceeded",
      "code": 0,
      "detail": "Hit a glitch. Try again."
    }
  ]
}
```

**Comment by Earlopain** [comment]
Huh

**Comment by Earlopain** [comment]
It'll continue where it error out now. The rate limit of course still exists and it will fail because of that but the retries will ensure it'll just keep on going until it eventually finishes.
